version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:password@localhost:5432/test_db"
      - image: cimg/postgres:14.10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      # Bundler & gem install
      - ruby/install-deps

      # Yarn install
      - node/install-packages:
          pkg-manager: yarn

      # DB setup
      - run:
          name: Setup Database
          command: |
            bin/rails db:create
            bin/rails db:schema:load

      # RSpec
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - build
